### ISSUE TITLE
Failed with exit code 1

### ISSUE THREAD

**Issue by gauloics** [NativeScript/template-master-detail-ng#76]
When i run 

> `tns create my-app-name --template tns-template-master-detail-ng`

then 

>`preinstall script running...`
`creating C:\...\my-app-name\firebase.nativescript.json...`
`creating C:\...\my-app-name\tslint.json...`
`Command npm.cmd install tns-template-master-detail-ng@3.2.0 --silent --save-exact --save failed with exit code 1`

use node v8.5.0
npm v5.4.2

**Comment by MIYankov** [comment]
@gauloics There is a known issue in npm 5.4.x that causes the templates to fail creation. The reason is npm 5.4.x is unable to install simultaneously two packages that have preinstall scripts. We have notified the guys that work on npm. Hopefully, an update will fix the issue. In the meantime you can downgrade your npm and the templates should work fine.

**Comment by gauloics** [comment]
Ops..., that's enough to stress me, I think there's a problem with my device. Thanks for the explanation.

**Comment by gauloics** [comment]
And now with npm@5.3.0 also failed :sob:

**Comment by MIYankov** [comment]
Can you elaborate what you mean by a local template? I'm not sure I understand what is failing on your side.

**Comment by gauloics** [comment]
At this articel [https://github.com/NativeScript/NativeScript/wiki/Using-the-%60tns-create%60-command](https://github.com/NativeScript/NativeScript/wiki/Using-the-%60tns-create%60-command)
the last point we can run 

> `tns create --template ~path/to/template`

that code from articel, but last night in my case `tns create my-app --template ~path/to/template`.
mis understand :laughing:

**Comment by MIYankov** [comment]
I tested cloning one of our repos and using the local tns create from template. It worked fine, so I guess you tried to develop your own template and the creation fails. We are currently working on a document that outlines how to create a proper app template.

In the meantime if you could share your template, perhaps in a repository, I could take a look and check out what is wrong.
