### ISSUE TITLE
js: ERROR typeerror......

### ISSUE THREAD

**Issue by nelsonwilliam11** [NativeScript/template-master-detail-ng#83]
js: ERROR TypeError: cannot read property 'view' of undefined

` onCarItemTap(args: ListViewEventData): void {
        const tappedCarItem = args.view.bindingContext;

        this._routerExtensions.navigate(["/cars/car-detail", tappedCarItem.id],
        {
            animated: true,
            transition: {
                name: "slide",
                duration: 200,
                curve: "ease"
            }
        });
    }
}
`

**Comment by MIYankov** [comment]
@nelsonwilliam11 I can't reproduce this issue with our template. Can you please share the contents of the `package.json` file in your project root?

**Comment by manoldonev** [comment]
@nelsonwilliam11 you can also try re-creating the app from scratch to verify whether the problem would resolve on your end with the latest version of the template as well. 

Use this CLI command:
```
tns create my-app-name --template tns-template-master-detail-ng
```

**Comment by nelsonwilliam11** [comment]
here is my package.json

{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.Groceries",
    "tns-android": {
      "version": "3.3.0-2017-9-29-1"
    }
  },
  "dependencies": {
    "@angular/animations": "~4.2.5",
    "@angular/common": "~4.2.5",
    "@angular/compiler": "~4.2.5",
    "@angular/core": "~4.2.5",
    "@angular/forms": "~4.2.5",
    "@angular/http": "~4.2.5",
    "@angular/platform-browser": "~4.2.5",
    "@angular/platform-browser-dynamic": "~4.2.0",
    "@angular/router": "~4.2.5",
    "email-validator": "^1.0.7",
    "nativescript-angular": "^4.2.0",
    "nativescript-camera": "^3.1.2",
    "nativescript-cardview": "^2.0.3",
    "nativescript-couchbase": "^1.0.18",
    "nativescript-facebook": "^2.0.1",
    "nativescript-file-photoview": "^0.1.5",
    "nativescript-floatingactionbutton": "^4.1.0",
    "nativescript-fresco": "^3.0.6",
    "nativescript-imagepicker": "^3.0.7",
    "nativescript-plugin-firebase": "^4.1.1",
    "nativescript-push-notifications": "^0.1.4",
    "nativescript-sqlite": "^1.1.9",
    "nativescript-telerik-ui": "^3.1.3",
    "nativescript-theme-core": "^1.0.4",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.4.3",
    "tns-core-modules": "^3.2.0",
    "zone.js": "0.8.2"
  },
  "devDependencies": {
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "lazy": "1.0.11",
    "nativescript-dev-android-snapshot": "^0.*.*",
    "nativescript-dev-typescript": "^0.4.0",
    "typescript": "2.2.2"
  }
}

**Comment by manoldonev** [comment]
@nelsonwilliam11 this package.json file does not seem to be based on the one generated by this app template (e.g. it is missing all of the SASS dependencies and most of the dependency versions seem to be set manually).

We would suggest you to use the following list of dependencies/devDependencies that this app template is tested and verified to work with (note all of them are fixed versions) as a starting point for your app:
``` json
{
  ...
  
  "dependencies": {
    "@angular/animations": "4.2.5",
    "@angular/common": "4.2.5",
    "@angular/compiler": "4.2.5",
    "@angular/core": "4.2.5",
    "@angular/forms": "4.2.5",
    "@angular/http": "4.2.5",
    "@angular/platform-browser": "4.2.5",
    "@angular/router": "4.2.5",
    "nativescript-angular": "4.2.0",
    "nativescript-imagepicker": "3.0.6",
    "nativescript-plugin-firebase": "4.1.1",
    "nativescript-telerik-ui": "3.1.1",
    "nativescript-theme-core": "1.0.4",
    "reflect-metadata": "0.1.10",
    "rxjs": "5.4.3",
    "tns-core-modules": "3.2.0",
    "zone.js": "0.8.17"
  },
  "devDependencies": {
    "codelyzer": "3.2.0",
    "nativescript-dev-sass": "1.3.2",
    "nativescript-dev-typescript": "0.5.1",
    "node-sass": "4.5.3",
    "tslint": "5.7.0",
    "typescript": "2.5.2"
  }
}
```

Also, we noticed that you seem to be using nativescript@next -- we would suggest you to try the current official version (3.2.1) as well.

**Comment by nelsonwilliam11** [comment]
@manoldonev  i did exactly what you said and it worked fine but when i put my app components i face the same problem

**Comment by manoldonev** [comment]
@nelsonwilliam11 Based on the provided information we cannot reproduce a problem with the app template. Can you provide a minimal step by step guide of your actions starting from the working template/package.json and resulting in the problem you are experiencing so we can try to assist you further?

**Comment by nelsonwilliam11** [comment]
the problem is i can't figure out what causes the problem all i do is i change the UI  according to my app

**Comment by nelsonwilliam11** [comment]
`
import { ListView } from "tns-core-modules/ui/list-view";
import { isAndroid } from "tns-core-modules/platform";
import * as imagepicker from "nativescript-imagepicker";
import {Image} from 'ui/image';
import {ImageSource} from 'image-source';

import { Car } from "../../shared/car.model";
import { CarService } from "../../shared/car.service";

import { registerElement } from "nativescript-angular/element-registry";
registerElement("Fab", () => require("nativescript-floatingactionbutton").Fab);

import { Demo } from "../../main-view-model";

import * as elementRegistryModule from 'nativescript-angular/element-registry';
elementRegistryModule.registerElement("CardView", () => require("nativescript-cardview").CardView);

import * as Facebook from "nativescript-facebook";
import { NavigationService } from "../../services/navigation.service";
import { config } from "../../app.config";
let http = require("http");
let appSettings = require("application-settings");
import * as fbLogout  from "nativescript-facebook";
import { ListViewEventData } from "nativescript-telerik-ui/listview";


import { SearchBar } from "ui/search-bar";
import { ListViewLinearLayout } from "nativescript-telerik-ui/listview";
import listViewModule = require("nativescript-telerik-ui/listview");
import { FrescoDrawee } from "nativescript-fresco";
import { StackLayout } from "ui/layouts/stack-layout";
import { Label } from "ui/label";
import { TabView, SelectedIndexChangedEventData, TabViewItem } from "ui/tab-view";
import { View } from "ui/core/view";

import { Router } from "@angular/router";
import { Component, OnInit, ChangeDetectorRef,ViewChild, ElementRef } from "@angular/core";
import { ObservableArray } from "data/observable-array";
import { DataItem } from "./dataItem";

import * as Application from "application";
import * as Timer  from "timer";
import { DataItemService } from "./dataItem.service";
import { RouterExtensions } from "nativescript-angular/router";






     
 @Component({
  selector: "main",  
  providers: [DataItemService, ],
  moduleId: module.id,
  templateUrl: "./main.html",
  styleUrls: ["./main-common.css"],

})
export class MainComponent implements OnInit  {
  private _dataItems: ObservableArray<DataItem>;
 private _staggeredItems: ObservableArray<DataItem>;
  private _layout: ListViewLinearLayout;

    
    public tabviewitems: Array<TabViewItem>;
public searchPhrase: string;

private _isLoading: boolean = false;
private _cars: ObservableArray<Car> = new ObservableArray<Car>([]);



     constructor( private _carService: CarService,private _routerExtensions: RouterExtensions,private _changeDetectionRef: ChangeDetectorRef, private _dataItemService: DataItemService, private ref: ChangeDetectorRef, private navigationService: NavigationService,private routerExtensions: RouterExtensions, private router: Router)
      
     {
        function pageLoaded(args) {
            var page = args.object;
            page.bindingContext = new Demo();
          }
          exports.pageLoaded = pageLoaded;
       
          
      this.tabviewitems = [];


}
get picturePlaceholderPath(): string {
    return '~/images/placeholder-img.jpg'
  };


       public tabIndexChanged(e: any) {

        switch (e.newIndex) {
            case 0:
                console.log(`Selected tab index: ${e.newIndex}`);
                break;
           case 1:
                console.log(`Selected tab index: ${e.newIndex}`);
                break;
           case 2:
                console.log(`Selected tab index: ${e.newIndex}`);
                break;
           case 4:
                console.log(`Selected tab index: ${e.newIndex}`);
                break;
                
            default:
                break;
        }
       }



     public tabViewIndexChange(res) {
        alert("Tab View selected index: " + res);

    }
    

    createTabItem(title: string, view: View): TabViewItem {
        const item = new TabViewItem();
        item.title = title;
        item.view = view;
        return item;


    
     } 
    
     ngOnInit(): void {
        
        this._dataItems = new ObservableArray<DataItem>(this._dataItemService.getListItemsFromJson());
        this._changeDetectionRef.detectChanges();
         this._staggeredItems = new ObservableArray<DataItem>(this._dataItemService.getStaggeredItems());
        this._changeDetectionRef.detectChanges();   
   }


    public get dataItems(): ObservableArray<DataItem> {
        return this._dataItems;
    }
     public get staggeredItems(): ObservableArray<DataItem> {
        return this._staggeredItems;
    }
    
    
    


   
     test(){
           this.routerExtensions.navigate(["/list"])
    
  }
     

  public onSubmit(args) {
        let searchBar = <SearchBar>args.object;
        alert("You are searching for " + searchBar.text);
    }

    public onTextChanged(args) {
        let searchBar = <SearchBar>args.object;
        console.log("SearchBar text changed! New value: " + searchBar.text);
    }
     logout() {
       
            this.routerExtensions.navigate(["/login"]);
        }


        items = [];
        
            onSelectMultipleTap() {
                let context = imagepicker.create({
                    mode: "multiple"
                });
                this.startSelection(context);
            }
        
            onSelectSingleTap() {
                let context = imagepicker.create({
                    mode: "single"
                });
                this.startSelection(context);
            }
        
            startSelection(context) {
                let _that = this;
        
                context
                .authorize()
                .then(() => {
                    _that.items = [];
                    return context.present();
                })
                .then((selection) => {
                    console.log("Selection done:");
                    selection.forEach(function (selected) {
                        console.log("----------------");
                        console.log("uri: " + selected.uri);
                        console.log("fileUri: " + selected.fileUri);
                    });
                    _that.items = selection;
                    _that._changeDetectionRef.detectChanges();
                }).catch(function (e) {
                    console.log(e);
                });
            
            }

            onCarItemTap(args: ListViewEventData): void {
            const tappedCarItem = args.view.bindingContext;
    
            this._routerExtensions.navigate(["sqlite", tappedCarItem.id],
            {
                animated: true,
                transition: {
                    name: "slide",
                    duration: 200,
                    curve: "ease"
                }
            });
        }
    }
        
`

**Comment by nelsonwilliam11** [comment]
`<ActionBar title='', style="background-color:#E9967A">
   <SearchBar hint="Search hint" [text]="searchPhrase" (textChange)="onTextChanged($event)" (submit)="onSubmit($event)" 
            color="white" textFieldBackgroundColor="#456" textFieldHintColor="white"></SearchBar>
             <Button text="Log out (custom)" (tap)="logout()"></Button>
    </ActionBar>
 <TabView #tabview (selectedIndexChanged)="tabIndexChanged($event)" toggleNavButton>
    <StackLayout *tabItem="{title: '', iconSource:'res://hh'}"> 
        <GridLayout tkExampleTitle tkToggleNavButton>
            <RadListView [items]="dataItems"  class="list-group">
                <ng-template tkListItemTemplate let-item="item">
                    <GridLayout class="listItemTemplateGrid">
                       
                                <StackLayout class="labelsStackLayout">
                                <Card:CardView margin="5" id="facebookCard" radius="30" elevation="15" class="whiteCard">
                                     <grid-layout  rows="auto, auto,250, auto,"  columns="60, auto, *" class="nelson" >
                                        <Label [text]="item.text" class="avatar-circle" [text]="item.text" textWrap="true" margin="10" row="0" col="0" />
                                        <Label [text]="item.name" textWrap="true" margin="10" class="ne"   row="0" col="1"> </Label>
                                        <Label [text]="item.text" textWrap="true" margin="10" class="nel"  row="0" col="1"></Label>
                                        <Label [text]="item.title" textWrap="true" margin="10" class="me"  row="1" colSpan="3" />
                                        <FrescoDrawee (tap)="onCarItemTap(picture)" row="2" colSpan="3" height="250" class="ho" stretch="aspectFill"[imageUri]="item.image"> </FrescoDrawee>                                         <grid-layout row="3" colSpan="3" rows="auto" columns="auto, auto, auto">
                                            <button text="rate" class="Material info clear-btn gray" col="0" />
                                            <button text="comment" class="Material info  gray" col="1" />
                                        </grid-layout>
                                    </grid-layout>  
                                </Card:CardView>
                               </StackLayout>
                    </GridLayout>
                    
                </ng-template>
                
                <ListViewGridLayout tkListViewLayout scrollDirection="Vertical" itemHight="200" spanCount="2"></ListViewGridLayout>
                
               
            </RadListView>   
         
               
                <FAB (tap)="fabTap()" icon="res://image" rippleColor="#f1f1f1" class="button"></FAB>
            </GridLayout>             
    </StackLayout>
    
    <StackLayout *tabItem="{title: '', iconSource:'res://noti'}">
                    
 
         </StackLayout>
      <StackLayout *tabItem="{title: '', iconSource:'res://aaa'}" >
               <camera></camera>
              </StackLayout>
    <StackLayout *tabItem="{title: '',iconSource:'res://tex' }" >
            <chat></chat>
              </StackLayout>
   
    <StackLayout *tabItem=  "{title: '', iconSource:'res://user' }" >
       
       <user></user>
       
    <StackLayout sdkToggleNavButton>
          </StackLayout>
          </StackLayout>

</TabView>


`

**Comment by nelsonwilliam11** [comment]
`{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.Myapp",
    "tns-android": {
      "version": "3.2.0"
    }
  },
  "dependencies": {
    "@angular/animations": "~4.2.5",
    "@angular/common": "~4.2.5",
    "@angular/compiler": "~4.2.5",
    "@angular/core": "~4.2.5",
    "@angular/forms": "~4.2.5",
    "@angular/http": "~4.2.5",
    "@angular/platform-browser": "~4.2.5",
    "@angular/platform-browser-dynamic": "~4.2.0",
    "@angular/router": "~4.2.5",
    "email-validator": "^1.0.7",
    "nativescript-angular": "^4.2.0",
    "nativescript-camera": "^3.1.2",
    "nativescript-cardview": "^2.0.3",
    "nativescript-couchbase": "^1.0.18",
    "nativescript-facebook": "^2.0.1",
    "nativescript-file-photoview": "^0.1.5",
    "nativescript-floatingactionbutton": "^4.1.0",
    "nativescript-fresco": "^3.0.6",
    "nativescript-imagepicker": "^3.0.7",
    "nativescript-plugin-firebase": "^4.1.1",
    "nativescript-push-notifications": "^0.1.4",
    "nativescript-sqlite": "^1.1.9",
    "nativescript-telerik-ui": "^3.1.3",
    "nativescript-theme-core": "^1.0.4",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.4.3",
    "tns-core-modules": "^3.2.0",
    "zone.js": "0.8.2"
  },
  "devDependencies": {
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "lazy": "1.0.11",
    "nativescript-dev-android-snapshot": "^0.*.*",
    "typescript": "2.2.2",
    "codelyzer": "3.2.0",
    "nativescript-dev-sass": "1.3.2",
    "nativescript-dev-typescript": "0.5.1",
    "node-sass": "4.5.3",
    "tslint": "5.7.0"
  }
}

`

**Comment by manoldonev** [comment]
@nelsonwilliam11 The source code pasted above is incomplete and rather incomprehensible in this form.

If providing a minimal step by step guide to reproduce the issue is not possible, can you provide a link to github repo containing a **runnable** stripped-down version of your app?

**Comment by nelsonwilliam11** [comment]
Yes sure

**Comment by nelsonwilliam11** [comment]
[


](url)
[my-app-name - Copy.zip](https://github.com/NativeScript/template-master-detail-ng/files/1378466/my-app-name.-.Copy.zip)

**Comment by manoldonev** [comment]
Your original error `js: ERROR TypeError: cannot read property 'view' of undefined` is caused by the fact that you have copied an event handler designed to work with the RadListView.itemTap event args and attached it to something else (FrescoDrawee.tap) that has different event args.

That said, we reviewed your app and it bears very little resemblance to the original master/detail template. Note that https://github.com/NativeScript/template-master-detail-ng/issues is not a general support channel -- you can use https://discourse.nativescript.org/ should you have further NativeScript inquiries.

**Comment by nelsonwilliam11** [comment]
Alright thanks soo much
