### ISSUE TITLE
Portrait to Landscape on iOS gives unexpected results

### ISSUE THREAD

**Issue by zurie** [NativeScript/template-master-detail-ng#87]
When viewing the default list of cars "car-list.component.html"  if you rotate your iPhone to landscape and back to portrait the List blows out width wise and you can scroll your view to the right showing a empty white space.

iOS 11 - Simulator / Device 11.0.2 (iPhone 7+)

**Comment by manoldonev** [comment]
I cannot reproduce this behavior in our local tests but we recently streamlined the car images in firebase as well.

Could you confirm whether you reproduce this in a brand-new application (either created from Sidekick, or with `tns create`)?

**Comment by zurie** [comment]
I created this brand new using sidekick. All you do is rotate the main view sideways and rotate back to portrait and once you do that you can scroll the portrait view left and right as the container still has the size of landscape.

**Comment by manoldonev** [comment]
@zurie You are correct, this again is an iOS 11 issue related to nativescript-telerik-ui@3.1.1 dependency in the current version of the Sidekick template. You can either manually update nativescript-telerik-ui dependency to 3.1.4 in your app, or re-create your app from scratch from the `master` branch of this repo that has the fixed dependencies out-of-the box:
```
tns create my-app-name --template https://github.com/NativeScript/template-master-detail-ng
```
We will be updating the Sidekick templates shortly so the iOS 11-related fixes will be available out-of-the-box for any new apps created from Sidekick.

**Comment by manoldonev** [comment]
Sidekick templates are updated to v3.2.2 and should include the iOS11 fixes out-of-the-box now.

**Comment by zurie** [comment]
thanks, upgrading to 3.1.4 fixes the issue
