### ISSUE TITLE
[iOS11] Slider fails to work on second press - also triggers History when set to 0 (too close to the edge for dragging)

### ISSUE THREAD

**Issue by zurie** [NativeScript/template-master-detail-ng#88]
When in edit mode, select the slider and change the price.  Without saving, try to select the slider again.  It is unresponsive.  If you select another input field and then go back to the slider it works again until you attempt to press it a third time.  Everytime you interact with it it becomes unselectable and needs interaction with another element before it responds to user touch.

Additionally, when dragging to 0, you are unable to reselect the slider because it triggers a navigation history event.

**Comment by manoldonev** [comment]
The slider issue on second press should be fixed in the next version of nativescript-angular: https://github.com/NativeScript/nativescript-angular/issues/887

As for the navigation history event trigger when dragging the slider to 0 -- we will consider how to improve this undesirable UX behavior.

**Comment by vakrilov** [comment]
Slider seems to be fixed now.
There is also a padding on the slider, so it is harder now to accidentally trigger back-swipe.
